### ISSUE TITLE
problem with encoded urls

### ISSUE THREAD

**Issue by ikkez** [bcosca/fatfree-core#121]
There seems to be an issue with encoded chars in urls. We got some responses about that issue 
https://github.com/bcosca/fatfree-core/pull/71#issuecomment-188882547
https://groups.google.com/forum/#!topic/f3-framework/4tSAHtDX2k8
I have not tested it yet by myself but it's probably related to: https://github.com/bcosca/fatfree-core/pull/71

**Comment by kavin-90** [comment]
Thanks @ikkez for creating Issue
<a href = "{{ @home_url }}/学園ベビーシッターズ">Gakuen Babysitters </a>
Route
/@series_name

That link works Direct but not via a href.tag

**Comment by xfra35** [comment]
@kavin-90 I can't reproduce your issue.
I've made a test case: https://paste.534f.de/4RZPFyuv

The following routes work as expected:

```
GET /page/学園ベビーシッターズ
POST /page/学園ベビーシッターズ
GET /page/страница
POST /page/страница
```

**Comment by kavin-90** [comment]
that works i know i posted how they didn't work.

**Comment by xfra35** [comment]
I don't get it.

Are you saying that your href contains "%E5%AD%A6%E5" and when you click on it you're sent to "%E5_%A6%E5"?

Have you checked which URL your browser is actually calling (using Firebug or Web Inspector for example)?

Also have you tried my test case? So that we work on the same code.

**Comment by ikkez** [comment]
@kavin-90 what OS, browser and test-server do you use? (versions)
cannot reproduce too.

**Comment by kavin-90** [comment]
@ikkez  Linux server centos 6.5.

@xfra35  url was end with / so obviously ITS F3 whose send it to non /

Direct url work but Somehow F3 redirect / ended url to non / that cause it. Browser show Redirecting Status code.

**Comment by xfra35** [comment]
Ok I got it now. Here's a new test case, that reproduces the issue: https://paste.534f.de/PWlYqare

The problem is coming from the use of `parse_url`, which is not UTF8-aware.

So when requesting `/page/学園ベビーシッターズ/` (with a trailing slash), the UTF-8 string gets broken [here](https://github.com/bcosca/fatfree-core/blob/b6a35586eabf074f746f84cf0f449e6c0e30c35b/base.php#L1434) and the framework redirects the browser to a malformed URI.

The `parse_url` function is used in 2 other places, so the bug may be present in those places too.

**Comment by KOTRET** [comment]
see [phpdocs](http://php.net/manual/de/function.parse-url.php#114817) for a (multibyte)fix

**Comment by kavin-90** [comment]
@xfra35 @KOTRET   thanks.

I checked 3.5.0 vs 3.5.1

differene is
`$this->hive['PARAMS']=$args=array_map('urldecode',$args);`

3.5.1
`$this->hive['PARAMS']=$args;`

**Comment by xfra35** [comment]
Fixed. I've removed the call to `parse_url`.

**Comment by ikkez** [comment]
It could be that the problem remains in the `mock` method now, because `PATH` and `QUERY` vars are not extracted from URI on the fly anymore and it only updates the `URI` variable here.
https://github.com/bcosca/fatfree-core/blob/5a5ce6253a75e63724d86d7fe89f565e6500827b/base.php#L1224
https://github.com/bcosca/fatfree-core/blob/5a5ce6253a75e63724d86d7fe89f565e6500827b/base.php#L1233

**Comment by xfra35** [comment]
This requires a bit of investigation indeed. It seems that `mock` expects an [URL-encoded](https://github.com/bcosca/fatfree/blob/a99a7632bf20bc42a1587fa16e447e6a1d55143e/app/router.php#L200) input, so it may be working after all.
