### ISSUE TITLE
Combined operator doesn't update SQL mapper

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree-core#143]
If we're having an integer field:
* `$mapper->foo = $mapper->foo + 1` triggers an `UPDATE` statement
* `$mapper->foo++` triggers an `UPDATE` statement
* `$mapper->foo += 1` does not

The same issue happens with combined concatenation operator: `$mapper->bar.=$string`.

After digging up a bit in the code, I found out that [this line](https://github.com/bcosca/fatfree-core/blob/0083673bea46fd2c6fd03fdaf32666824b0f1c00/db/sql/mapper.php#L93) returns FALSE. In other words, when `set()` is called, `$this->fields[$key]['value']` equals `$val`, so the field doesn't get marked as "changed".

I'm scratching my head to understand what's going on here... Looks like there's some reference assignment messing up...

**UPDATE**
That definitely looks like something with references because that bug showed up while upgrading a project from 3.2 to 3.5. In 3.2, `Magic->get()` was not returning a reference.

**Comment by ikkez** [comment]
I had a similar issue in cortex once ago. It's true that the reference is already updated when we process the magic setter. I worked around it which a hook in the `ArrayAccess` setter. 

Option A could be to add this method:

```php
public function offsetSet($key, $val) {
	$this->fields[$key]['changed']=TRUE;
	parent::offsetSet($key,$val);
}
```
and add a false case for the condition [here](https://github.com/bcosca/fatfree-core/blob/0083673bea46fd2c6fd03fdaf32666824b0f1c00/db/sql/mapper.php#L93) to invalidate the changed flag, so it becomes:

```php
if ($this->fields[$key]['value']!==$val ||
	$this->fields[$key]['default']!==$val && is_null($val))
	$this->fields[$key]['changed']=TRUE;
else
	$this->fields[$key]['changed']=FALSE;
```

Another way I had in mind is to extend the condition and add another check with the (original?) mapper within the `$query` property:

```php
if ($this->fields[$key]['value']!==$val ||
	$this->query[$this->ptr]->fields[$key]['value']!==$val ||
	$this->fields[$key]['default']!==$val && is_null($val))
	$this->fields[$key]['changed']=TRUE;
```

This might look like an easier fix now, but actually I am wondering why the mapper properties in the $query array isn't already referenced and updated to match the active loaded record on `$this`.
I think I noticed that once before already and thought it would maybe be better to get rid of the query property in **each** mapper.. even worse that these do not seem to be references. That's maybe something to refactor for v4.

**Comment by xfra35** [comment]
There are many things that I don't understand here:
* why `$mapper->foo+=1` directly updates the reference while `$mapper->foo++` doesn't
* why do we need `Magic->get()` to return a reference
* how your option A is supposed to work ^^ (at the time `offsetSet` is called, or even `__set`, the reference has already been updated)
* how does your option B work (it does indeed!)
* if the bug should be fixed in `Mapper` or `Magic`

Here's a small script to reproduce the issue, only with the `Magic` class:

```php
class Game extends Magic {
    protected $data=[];
    function exists($key){return array_key_exists($key,$this->data);}
    function set($key,$val){
        echo sprintf("$key will switch from %s to $val<br>",@$this->data[$key]?:'<em>empty</em>');
        return $this->data[$key]=$val;
    }
    function &get($key){return $this->data[$key];}
    function clear($key){unset($this->data[$key]);}
}
$game=new Game;
$game->score=10;// score will switch from empty to 10
$game->score++;// score will switch from 10 to 11
$game->score+=2;// score will switch from 13 to 13
```

**Comment by ikkez** [comment]
> why $mapper->foo+=1 directly updates the reference while $mapper->foo++ doesn't

I'm not completly sure but I think it has to do something with how php handles these operators. I had a similar issue with adding array values, like `$mapper->foo[] = 'bar'`. If php has the reference, it's updated nearly instantly.. which is good in a performance-wise. if you set a value to a property, it seems *only* processed by the setter.

> why do we need Magic->get() to return a reference

Because it would not be writable otherwise with those shortcut operators... espcially this array push samle `$mapper->foo[] = 'bar'` would fail. I think there is an old issue about that somewhere.

> how your option A is supposed to work ^^ (at the time offsetSet is called, or even __set, the reference has already been updated)

It just ensures that, if a value is set, the changed flag is triggered... in the 2nd step the value is checked.. if it is different from the initial value, it stays on, otherwise switched back to off... so it does not update if you set the same value as it was initially.

> how does your option B work (it does indeed!)

when the mapper is hydrated with records, it clones the mapper from the query result right here: https://github.com/bcosca/fatfree-core/blob/master/db/sql/mapper.php#L169
this option works, because I compare the value with the hidden mapper behind the scene, where the pointer `$this->ptr` shows at.. that mapper seems to be still untouched.

I'm not completly done with my investigation, but I'm out to vacation the next days. I can support you next week again on this. good luck =)

**Comment by ikkez** [comment]
should be fixed now :)

**Comment by xfra35** [comment]
Thanks. That fixes it for SQL mappers.

Anyway, the test case for `Magic` (as described above) still fails.

And also references still don't trigger an `UPDATE` statement:

```php
$foo=&$mapper->foo;
$foo=123;
echo $mapper->foo; // 123
$mapper->save(); // nothing
```

But I'm wondering if we can do anything about this...

**Comment by ikkez** [comment]
Your Magic test case is not wrong, it indeed stores the correct values, when using the magic getter/setter properties. That's what it's about and it does its job very well.

**Comment by xfra35** [comment]
Hmm what you're saying is that we can't beat PHP on this ^^

I think there are two things here:

1. references are indeed updated before `__set`, which is probably the behavior expected by PHP devs... but you really need to be aware of it!
2. the combined operator `+=` seems to work by reference, even though the [documentation](http://php.net/manual/en/language.operators.assignment.php) says the contrary: `Note that the assignment copies the original variable to the new one (assignment by value) $a += 5; // as if we had said: $a = $a + 5;`
